#!/usr/bin/env bash

print () {
    destnation=$(dig "$2.$1" +short)
    echo "The subdomain "$2" is a A record and points to "$destnation""
}

domain=$1
sub_domain=$2

if [ $# -eq 1 ]; then
    print "$1" "www"
    print "$1" "lb-01"
    print "$1" "web-01"
    print "$1" "web-02"
else
    print  "$domain" "$sub_domain"
fi
