#!/usr/bin/env bash
# Configure your domain zone so that the subdomains points to your load-balancer IP
# and a Bash script that will display information about subdomains.

print () {
    destnation=$(dig "$2.$1" +short)
    record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{print $3}' | tail -n 1)
    echo "The subdomain "$2" is a "$record" record and points to "$destnation""
}

domain=$1
sub_domain=$2

if [ $# -eq 1 ]; then
    print "$1" "www"
    print "$1" "lb-01"
    print "$1" "web-01"
    print "$1" "web-02"
elif [ $# -eq 2 ]; then
    print  "$domain" "$sub_domain"
fi
