#!/usr/bin/env bash
# Install and setup nginx
sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 -R /var/www/html/
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
