#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  WebTraffic-frontend
        bind *:80
        mode http
        default_backend WebTraffic-backend
backend WebTraffic-backend
        balance roundrobin
        server 124571-web-01 54.175.224.158:80 check
        server 124571-web-02 100.25.129.156:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
