#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it.

name_format=$(date +"%d-%m-%Y")
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$name_format".tar.gz backup.sql
