#!/usr/bin/env bash
# choose: answere the following question

# What is the OSI model?

#   1. Set of specifications that network hardware manufacturers must respect
#   2. The OSI model is a conceptual model that characterizes the communication
#      functions of a telecommunication system without regard to their underlying internal structure and technology
#   3. The OSI model is a model that characterizes the communication functions
#      of a telecommunication system with a strong regard for their underlying internal structure and technology
echo "3"
# How is the OSI model organized?

#   1. Alphabetically
#   2. From the lowest to the highest level
#   3. Randomly
echo "2"
