#!/usr/bin/env bash
# choose: answere the following question
# What type of network a computer in local is connected to?

#    Internet
#    WAN
#    LAN
1
# What type of network could connect an office in one building to another office in a building a few streets away?

#    Internet
#    WAN
#    LAN
2
# What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?

#    Internet
#    WAN
#    LAN
3
