#!/usr/bin/env bash
# choose: answere the following question

# Which statement is correct for the TCP box:
#    It is a protocol that is transferring data in a slow way but surely
#    It is a protocol that is transferring data in a fast way and might loss data along in the process
echo "1"
# Which statement is correct for the UDP box:
#    It is a protocol that is transferring data in a slow way but surely
#    It is a protocol that is transferring data in a fast way and might loss data along in the process
echo "2"
# Which statement is correct for the TCP worker:
#    Have you received boxes x, y, z?
#    May I increase the rate at which I am sending you boxes?
echo "1"
