#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

sudo apt -y update
sudo apt-get -y install nginx
sudo apt-get -y install ufw
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
