#!/usr/bin/env bash
# Creates the file '/var/run/myscript.pid' containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ | sudo tee /var/run/myscript.pid > /dev/null

remove="sudo rm -f /var/run/myscript.pid"

trap "echo Y U no love me?!" SIGINT
trap 'echo "I hate the kill command"; $remove; exit' SIGTERM SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
