#!/usr/bin/env bash
# Creates the file '/var/run/myscript.pid' containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo echo $$ >> /var/run/holbertonscript.pid

remove="rm -f /var/run/holbertonscript.pid"

trap "echo I hate the kill command ; $remove ; exit" SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGINT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
