#!/usr/bin/env bash
# This script allows to start, stop, and restart the manage_my_process script

usage() {
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
}

start () {
    bash manage_my_process &
    echo $! | sudo tee /var/run/my_process.pid > /dev/null
}

stop () {
    pid=$(cat /var/run/my_process.pid)
    kill "$pid"
    sudo rm /var/run/my_process.pid
}

restart () {
    stop
    start
}

if [ "$1" == "start" ]; then
    start
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    stop
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    restart
    echo "manage_my_process restarted"
else
    usage
fi
